---
- name: Deploy, configure, and populate Postgres 10
  hosts: database_servers
  become: true
  gather_facts: false
  tags:
    - database_servers

  roles:
  - postgres


- name: End to end smoke tests
  hosts: app_servers:database_servers
  gather_facts: true
  become: true
  tags:
    - smoketest  

  tasks:
    - name: Need this to run smoke test
      yum:
        name: python-psycopg2
      delegate_to: "{{ groups.app_servers[0] }}"
      run_once: true
      tags:
        - smoketest

    - name: Smoketest Postgres database
      postgresql_ping:
        db: flask_db
        login_host: "{{ groups.database_servers[0] }}"
#        login_host: "{{ hostvars[groups.database_servers[0]]['ansible_host'] }}"
        login_user: flask
        login_password: redhat
        ssl_mode: disable
      delegate_to: "{{ groups.app_servers[0] }}"
      run_once: true
      tags:
        - smoketest

